version: "3"
services:
  send-legal-mail-api-db:
    image: postgres:13.3
    networks:
      - hmpps
    container_name: send-legal-mail-api-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=send_legal_mail_api_db

  mailcatcher:
    image: sj26/mailcatcher
    networks:
      - hmpps
    ports:
      - '1080:1080'
      - '1025:1025'

  localstack:
    image: localstack/localstack:0.13.1
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
