standalone-redis:
  # enable keyspace notifications when running in standalone redis (unsupported for elasticache)
  keyspace-notifications: 'Ex'

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
  data:
    redis:
      port: 6378

hmpps:
  auth:
    url: http://localhost:9090/auth
manage:
  users:
    api:
      url: https://manage-users-api-dev.hmpps.service.justice.gov.uk
prisoner:
  search:
    url: http://localhost:9092
prison:
  register:
    url: https://prison-register-dev.hmpps.service.justice.gov.uk

# Refer to the README - Signing the JWT section to get below keys
app:
  jwt:
    private-key: '<replace with kubernetes secret>'
    public-key: '<replace with kubernetes secret>'
    expiry: 1d
  s3:
    localstack-url: http://127.0.0.1:4566
    region: eu-west-2
    bucket-name: cjsm-orgs
  notify:
    apikey: dummy-api-key
