standalone-redis:
  # enable keyspace notifications when running in standalone redis (unsupported for elasticache)
  keyspace-notifications: 'Ex'

spring:
  redis.port: 6378

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

hmpps:
  auth:
    url: http://localhost:9090/auth