standalone-redis:
  # enable keyspace notifications when running in standalone redis (unsupported for elasticache)
  keyspace-notifications: 'Ex'

spring:
  redis.port: 6378

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
  mail:
    password: mailuser
    username: mailpass
    host: localhost
    port: 1025
    protocol: smtp
    test-connection: false

mailcatcher.api.port: 1080

hmpps:
  auth:
    url: http://localhost:9090/auth