apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetes
name: send-legal-mail-to-prisons-api
version: 0.2.0
dependencies:
  - name: generic-service
    version: "3.6.2"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-prometheus-alerts
    version: 1.11.2
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
