generic-service:
  nameOverride: send-legal-mail-to-prisons-api
  serviceAccountName: send-legal-mail-to-prisons
  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/send-legal-mail-to-prisons-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: send-legal-mail-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /cjsm/directory/refresh {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SPRING_DATA_REDIS_SSL_ENABLED: "true"
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    send-legal-mail-to-prisons-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      APP_JWT_PUBLICKEY: "JWT_PUBLIC_KEY"
      APP_JWT_PRIVATEKEY: "JWT_PRIVATE_KEY"
      APP_NOTIFY_API_KEY: "NOTIFY_API_KEY"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    slmtp-api-elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"
    send-legal-mail-s3-bucket-output:
      APP_S3_BUCKET_ARN: "bucket_arn"
      APP_S3_BUCKET_NAME: "bucket_name"

  allowlist:
    groups:
      - internal

  resources:
    requests:
      memory: 512Mi

generic-prometheus-alerts:
  targetApplication: send-legal-mail-to-prisons-api

cron:
  cjsmDirectorySchedule: "15 3 * * *"

