# Per environment values which override defaults in send-legal-mail-to-prisons-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-api-preprod.prison.service.justice.gov.uk
    contextColour: green

  allowlist:
    groups:
      - circleci
      - internal

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    MANAGE_USERS_API_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    PRISON_REGISTER_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: send-legal-mail-alerts-nonprod
