---
# Per environment values which override defaults in send-legal-mail-to-prisons-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-api.prison.service.justice.gov.uk
    contextColour: green

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    APP_MAGICLINK_URL: https://send-legal-mail.prison.service.justice.gov.uk/link/verify-link

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: farsight-alerts
