# Per environment values which override defaults in send-legal-mail-to-prisons-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-api-dev.prison.service.justice.gov.uk
    contextColour: green

  allowlist:
    groups:
      - circleci
      - internal

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    MANAGE_USERS_API_URL: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    PRISON_REGISTER_URL: https://prison-register-dev.hmpps.service.justice.gov.uk
    APP_JWT_EXPIRY: 1d
    APP_BARCODE_EXPIRY: 2d
    APP_BARCODE_RANDOM_CHECK_PERCENTAGE: 25

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: send-legal-mail-alerts
  businessHoursOnly: true

cron:
  barcodeStatsReportSchedule: "5 8 * * 1-5"
  cjsmDirectorySchedule: "*/15 * * * *"

